language: node_js

node_js: stable
cache:
  directories:
    - node_modules
    - public

before_install:
  - git config --global user.name "${gitconf_username}"
  - git config --global user.email "${gitconf_email}"


install:
  - "npm install"

script:
  #然后编辑发布线上版本
  - npm run build
  - mkdir publish
  - cp ./static ./publish/static -rf
  - cp ./index.html ./publish/index.html -rf
  - echo "blog.zz173.com" > ./publish/CNAME
   #进入gh-pages发布逻辑
  - cd publish
   # 开始计算js的新名字
  - jsName=$(ls static|grep \.js)
   #jsName="${jsName}?sign=$(date +%s)"
  - echo "modfiy js filename to:$jsName"
  - sed -i "s/build\.js/$jsName/g" ./index.html
  - cp index.html 404.html
  - echo "" > .gitignore
  - git init
  - git add .
  - git commit -am "publish"
  - git push --force --quiet https://${github_token}@${github_ref} master:gh-pages
  - cd ../
   # 清理资源
  - rm -rf ./publish
  - rm -rf ./static
  - echo "everything ok!"


branches:
  only:
    - master
